packages:
  - apps/*
  - packages/*

catalog:
  tools:
    tsdown: ^0.15.6
    typescript: ^5.0.0

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - tesseract.js
  - unrs-resolver
