packages:
  - apps/*
  - packages/*

catalog:
  tsdown: ^0.15.6
  typescript: ^5.0.0

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - better-sqlite3
  - tesseract.js
  - unrs-resolver
